// src/presentations/views/Home/localComponents/JoinDialog/index.vue
<template>
  <g-Dialog v-if="isVisible" title="JOIN">
    <template v-slot:content>
      <div class="u-mb20">
        <g-Button size="large" full @click="join">JOIN</g-Button>
        <p class="note">VRChatを新しく再起動し、インスタンスにJOINする</p>
      </div>
      <div>
        <g-Button size="large" full @click="inviteMe">INVITE ME</g-Button>
        <p class="note">自分自身にインスタンスへのInviteを送信する</p>
      </div>
    </template>
    <template v-slot:buttonArea>
      <g-Button color="gray" @click="hide">閉じる</g-Button>
    </template>
  </g-Dialog>
</template>

<script lang="ts" src="./script.ts" />
<style lang="scss" src="./style.scss" scoped />

// src/presentations/components/container/FriendLocationContainerComponent/components/FriendLocationComponent/components/WorldInfoComponent/components/JoinDialogComponent/JoinDialogComponent.tsx
import { DialogComponent } from '../../../../../../../../presentational/DialogComponent/DialogComponent'
import styles from './style.module.scss'
import { ButtonComponent } from '../../../../../../../../presentational/ButtonComponent/ButtonComponent'
import { Instance } from '../../../../../../../../../types'
import { useFullLoader } from '../../../../../../../../../providers/FullLoader/useFullLoader'
import { useToast } from '../../../../../../../../../providers/Toasts/useToast'
import { ToastTypes } from '../../../../../../../../../providers/Toasts/types'

type Props = {
  instance: Instance
  isVisible: boolean
  inviteMe: (instance: Instance) => Promise<void>
  hide: () => void
}
export const JoinDialogComponent = (props: Props) => {
  const fullLoader = useFullLoader()
  const { toast } = useToast()

  const join = () => {
    window.location.href = `vrchat://launch?id=${props.instance.id}`
  }

  const onClickInviteMe = async () => {
    fullLoader.show()
    await props.inviteMe(props.instance).finally(() => {
      fullLoader.hide()
    })
    toast({
      type: ToastTypes.Success,
      content:
        'Inviteの送信に成功しました（VRChat内で届くまではタイムラグがあります）',
    })
    props.hide()
  }

  return (
    <DialogComponent
      isVisible={props.isVisible}
      title="JOIN"
      contentSlot={
        <>
          <div className="u-mb20">
            <ButtonComponent size="large" isFull onClick={join}>
              <span>JOIN</span>
            </ButtonComponent>
            <p className={styles.note}>
              VRChatを新しく再起動し、インスタンスにJOINする
            </p>
          </div>
          <div>
            <ButtonComponent size="large" isFull onClick={onClickInviteMe}>
              <span>INVITE ME</span>
            </ButtonComponent>
            <p className={styles.note}>
              自分自身にインスタンスへのInviteを送信する
            </p>
          </div>
        </>
      }
      buttons={[
        <ButtonComponent color="gray" onClick={props.hide}>
          <span>閉じる</span>
        </ButtonComponent>,
      ]}
    />
  )
}
