// src/presentations/App/localComponents/Menu/localComponents/SettingDialog/index.vue
<template>
  <g-Dialog class="c-settingDialog" title="設定">
    <template v-slot:content>
      <div class="settingList">
        <div class="settingList_item">
          <div class="settingItem">
            <div class="settingItem_left">
              <div class="settingItem_title">通知音</div>
              <div class="settingItem_note">
                OSの通知音と重複する場合はOFFにしてください
              </div>
            </div>
            <div class="settingItem_input">
              <g-Toggle
                :value="setting.enableNotificationSound"
                @input="onChangeEnableNotificationSound"
              />
            </div>
          </div>
        </div>
        <div class="settingList_item">
          <div class="settingItem">
            <div class="settingItem_left">
              <div class="settingItem_title">ダークモード</div>
              <div class="settingItem_note"></div>
            </div>
            <div class="settingItem_input">
              <g-Toggle
                :value="setting.theme === 'dark'"
                @input="onChangeDarkMode"
              />
            </div>
          </div>
        </div>
        <div class="settingList_item">
          <div class="settingItem">
            <div class="settingItem_left">
              <div class="settingItem_title">メインカラー</div>
              <div class="settingItem_note"></div>
            </div>
            <div class="settingItem_input">
              <g-Select
                class="u-mr5"
                :items="[
                  {
                    label: 'グリーン',
                    value: 'green',
                  },
                  {
                    label: 'レッド',
                    value: 'red',
                  },
                  {
                    label: 'ブルー',
                    value: 'blue',
                  },
                  {
                    label: 'イエロー',
                    value: 'yellow',
                  },
                  {
                    label: 'オレンジ',
                    value: 'orange',
                  },
                ]"
                :value="setting.mainColor"
                @input="onChangeMainColor"
              />
            </div>
          </div>
        </div>
      </div>
    </template>
    <template v-slot:buttonArea>
      <g-Button @click="hideSettingDialog">閉じる</g-Button>
    </template>
  </g-Dialog>
</template>

<script lang="ts" src="./script.ts" />
<style lang="scss" src="./style.scss" scoped />

// src/presentations/App/components/HeaderContainerComponent/components/MenuComponent/components/SettingDialogComponent/SettingDialogComponent.tsx
import { DialogComponent } from '../../../../../../../components/presentational/DialogComponent/DialogComponent'
import { ButtonComponent } from '../../../../../../../components/presentational/ButtonComponent/ButtonComponent'
import styles from './style.module.scss'
import { ToggleComponent } from '../../../../../../../components/presentational/ToggleComponent/ToggleComponent'
import { Color, Colors, Themes } from '../../../../../../../Colors'
import { SelectComponent } from '../../../../../../../components/presentational/SelectComponent/SelectComponent'
import { Setting } from '../../../../../../../types'

const selectItems = [
  {
    label: 'グリーン',
    value: Colors.Green,
  },
  {
    label: 'レッド',
    value: Colors.Red,
  },
  {
    label: 'ブルー',
    value: Colors.Blue,
  },
  {
    label: 'イエロー',
    value: Colors.Yellow,
  },
  {
    label: 'オレンジ',
    value: Colors.Orange,
  },
]

type Props = {
  isVisible: boolean
  setting: Setting
  onChangeSetting: (setting: Setting) => void
  hide: () => void
}
export const SettingDialogComponent = (props: Props) => {
  const onChangeEnabledNotificationSound = (checked: boolean) => {
    props.onChangeSetting({
      ...props.setting,
      enableNotificationSound: checked,
    })
  }

  const isDarkMode = props.setting.theme === Themes.Dark
  const onChangeTheme = (checked: boolean) => {
    props.onChangeSetting({
      ...props.setting,
      theme: checked ? Themes.Dark : Themes.Light,
    })
  }

  const onChangeMainColor = (color: Color) => {
    props.onChangeSetting({
      ...props.setting,
      mainColor: color,
    })
  }

  return (
    <DialogComponent
      isVisible={props.isVisible}
      title="設定"
      contentSlot={
        <div className={styles.settingList}>
          <div className={styles.settingListItem}>
            <div className={styles.settingItem}>
              <div className={styles.settingItemLeft}>
                <div className={styles.settingItemTitle}>通知音</div>
                <div className={styles.settingItemNote}>
                  OSの通知音と重複する場合はOFFにしてください
                </div>
              </div>
              <div className={styles.settingItemInput}>
                <ToggleComponent
                  checked={props.setting.enableNotificationSound}
                  onChange={onChangeEnabledNotificationSound}
                />
              </div>
            </div>
          </div>

          <div className={styles.settingListItem}>
            <div className={styles.settingItem}>
              <div className={styles.settingItemLeft}>
                <div className={styles.settingItemTitle}>ダークモード</div>
                <div className={styles.settingItemNote} />
              </div>
              <div className={styles.settingItemInput}>
                <ToggleComponent
                  checked={isDarkMode}
                  onChange={onChangeTheme}
                />
              </div>
            </div>
          </div>

          <div className={styles.settingListItem}>
            <div className={styles.settingItem}>
              <div className={styles.settingItemLeft}>
                <div className={styles.settingItemTitle}>メインカラー</div>
                <div className={styles.settingItemNote} />
              </div>
              <div className={styles.settingItemInput}>
                <SelectComponent
                  items={selectItems}
                  value={props.setting.mainColor}
                  onChange={onChangeMainColor}
                />
              </div>
            </div>
          </div>
        </div>
      }
      buttons={[
        <ButtonComponent onClick={props.hide}>
          <span>閉じる</span>
        </ButtonComponent>,
      ]}
    />
  )
}
