// src/presentations/components/container/FriendLocationContainerComponent/components/FriendLocationComponent/components/UserListItemComponent/components/UnfavoriteDialogComponent/UnfavoriteDialogComponent.tsx
import { Friend } from '../../../../../../../../../types'
import { DialogComponent } from '../../../../../../../../presentational/DialogComponent/DialogComponent'
import { ButtonComponent } from '../../../../../../../../presentational/ButtonComponent/ButtonComponent'

type Props = {
  friend: Friend
  onClickUnfavorite: () => void
  isVisible: boolean
  hide: () => void
}
export const UnfavoriteDialogComponent = (props: Props) => {
  return (
    <DialogComponent
      isVisible={props.isVisible}
      title={`Unfavorite ${props.friend.displayName}`}
      contentSlot={
        <>
          <div className="u-mb20">
            {props.friend.displayName}のお気に入りを解除しますか？
          </div>
        </>
      }
      buttons={[
        <ButtonComponent onClick={props.hide}>
          <span>閉じる</span>
        </ButtonComponent>,
        <ButtonComponent color="danger" onClick={props.onClickUnfavorite}>
          <span>Unfavorite</span>
        </ButtonComponent>,
      ]}
    />
  )
}

// src/presentations/views/Home/localComponents/UnfavoriteDialog/index.vue
<template>
  <g-Dialog :title="`Unfavorite ${friend.displayName}`">
    <template v-slot:content>
      <div class="u-mb20">
        {{ friend.displayName }}のお気に入りを解除しますか？
      </div>
    </template>
    <template v-slot:buttonArea>
      <g-Button class="u-mr20" @click="hide">閉じる</g-Button>
      <g-Button class="u-mr20" color="primary" @click="unfavoriteButtonHandler"
        >Unfavorite</g-Button
      >
    </template>
  </g-Dialog>
</template>

<script lang="ts" src="./script.ts" />
<style lang="scss" src="./style.scss" scoped />
