// src/presentations/components/Toggle/index.vue
<template>
  <label class="c-toggle">
    <input
      type="checkbox"
      class="input"
      @change="$emit('input', $event.target.checked)"
      :checked="value"
    />
    <span class="body" />
  </label>
</template>

<script lang="ts" src="./script.ts" />
<style lang="scss" src="./style.scss" scoped />

// src/presentations/components/presentational/ToggleComponent/ToggleComponent.tsx
import styles from './style.module.scss'

type Props = {
  checked: boolean
  onChange: (checked: boolean) => void
}
export const ToggleComponent = (props: Props) => {
  const onChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const checked = event.target.checked
    props.onChange(checked)
  }

  return (
    <label className={styles.root}>
      <input
        type="checkbox"
        className={styles.input}
        onChange={onChange}
        checked={props.checked}
      />
      <span className={styles.body} />
    </label>
  )
}
